[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_todo_list_app = "ib2VcJC9hEdyeEPsJT9NYryjVTGH41kU6u1zsnWR19q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
